### ISSUE TITLE
there is no train file in the link!

### ISSUE THREAD

**Issue by Mayar2009** [kabirahuja2431/FineTuneBERT#3]
https://nlp.stanford.edu/sentiment/

I found that this link contains the train file but in txt format
could you please explain what should we use ?

**Comment by kabirahuja2431** [comment]
You can find the The Stanford Sentiment Treebank dataset from here: https://gluebenchmark.com/tasks

**Comment by Mayar2009** [comment]
thanks!
when I tried to execute the model I met the following error 
I am still learning so I need your help if it is possible
python -m src.main -gpu 0 -maxlen 32 -batch_size 32 -lr 0.00005 -max_eps 4
Building model! (This might take time if you are running this for first time)
Done in 18.410780906677246 seconds
Creating criterion and optimizer objects
Done in 0.027838706970214844 seconds
Creating train and val dataloaders
Done in 3.9232983589172363 seconds
Let the training begin
Traceback (most recent call last):
  File "C:\Anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\FineTuneBERT-master\src\main.py", line 109, in <module>
    train(net, criterion, opti, train_loader, val_loader, args)
  File "C:\FineTuneBERT-master\src\main.py", line 59, in train
    opti.step()
  File "C:\Anaconda\lib\site-packages\torch\optim\adam.py", line 103, in step
    denom = (exp_avg_sq.sqrt() / math.sqrt(bias_correction2)).add_(group['eps'])
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 2.00 GiB total capacity; 1.34 GiB already allocated; 11.80 MiB free; 1.40 GiB reserved in total by PyTorch)

**Comment by kabirahuja2431** [comment]
This means that there is not enough memory in your GPU to run the code. Generally in such cases reducing the batch size helps, but with just 11.8 MiB free, I don't think it will be possible to run this code on your GPU. Another thing that you can do is run this code on CPU, but that will be very slow. In that case you can just finetune the classification layer and no the entire BERT model. that will get some hit in performance but will train quickly. Just put -freeze_bert argument in your execution command like this:

 python -m src.main -gpu 0 -maxlen 32 -batch_size 8 -lr 0.00005 -max_eps 4 -freeze_bert

**Comment by Mayar2009** [comment]
thanks for your patient !
now I have another error 
Iteration 8400 of epoch 0 complete. Loss : 0.25744470953941345 Accuracy : 1.0
Epoch 0 complete! Validation Accuracy : 0.8279815912246704, Validation Loss : 0.4243849364169147
Best validation accuracy improved from 0 to 0.8279815912246704, saving model...
Traceback (most recent call last):
  File "C:\Anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\FineTuneBERT-master\src\main.py", line 109, in <module>
    train(net, criterion, opti, train_loader, val_loader, args)
  File "C:\FineTuneBERT-master\src\main.py", line 71, in train
    torch.save(net.state_dict(), 'Models/sstcls_{}_freeze_{}.dat'.format(ep, args.freeze_bert))
  File "C:\Anaconda\lib\site-packages\torch\serialization.py", line 327, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "C:\Anaconda\lib\site-packages\torch\serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Anaconda\lib\site-packages\torch\serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'Models/sstcls_0_freeze_True.dat'

**Comment by kabirahuja2431** [comment]
It's because there is no Models directory from where you are running your code. Just do mkdir Models in FineTuneBERT and it should work.

**Comment by Mayar2009** [comment]
thanks very much every thing is working mow!
Iteration 8300 of epoch 3 complete. Loss : 0.3120574355125427 Accuracy : 0.875
Iteration 8400 of epoch 3 complete. Loss : 0.1342129111289978 Accuracy : 1.0
Epoch 3 complete! Validation Accuracy : 0.83600914478302, Validation Loss : 0.3616518953114475
Best validation accuracy improved from 0.8348623514175415 to 0.83600914478302, saving model...
Done in 4878.9678592681885 seconds


thank you!

**Comment by Mayar2009** [comment]
the last question please how can we use the saved models?

**Comment by kabirahuja2431** [comment]
Please check Pytorch's documentation on how to load saved models. Once you have loaded a pre-trained model, follow the steps for preprocessing a sentence according to BERT's specifications, convert it to a tensor and feed it to the model.
